# Generated by Django 4.1.5 on 2023-04-30 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tourist', '0002_category_alter_tourist_options_tourist_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourist',
            options={'ordering': ['id'], 'verbose_name': 'Көрікті жерлер', 'verbose_name_plural': 'Көрікті жерлер'},
        ),
        migrations.AddField(
            model_name='tourist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
